
import '../styles/globals.css'


import { Antonio } from 'next/font/google'

import { Libre_Baskerville } from 'next/font/google'



const antonio = Antonio({ subsets: ['latin'], weight: "400", })
// const libre_baskerville = Libre_Baskerville({ subsets: ['latin'] })

export const metadata = {
  title: 'Durodola Abdulhad',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${antonio.className} bg-light-white`}>
        {/* Header */}
        <main className="bg-deep-black">
          <div className="max-w-8xl mx-auto ">
            {children}
          </div>
        </main>

      </body>
    </html>
  )
}
