

import "../styles/globals.css";

import { fonts } from "../fonts/font";
import Footer from "@/components/site/Footer/Footer";
import { getContactInfo } from "@/schemas/utils/sanity.utils";
import Layout from "@/components/site/Navbars/NavbarLayout";

export const metadata = {
  title: "Durodola Abdulhad",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

    // const contactInfo = await getContactInfo();
  return (
    <html lang="en">
      <body
        className={`${fonts.antonio.variable} ${fonts.sohneBold.variable} ${fonts.migraLight.variable} ${fonts.libre_baskerville.variable} bg-transparent `}
      >
        {/* Header */}
        <main className="bg-transparent ">
          <div className="max-w-8xl mx-auto ">
            {children}

            {/* <Layout route="/custom">
              <Footer footer={contactInfo} />
            </Layout> */}
          </div>
        </main>
      </body>
    </html>
  );
}
