// import Header from '@/components/Header'
import Header from '../../components/Header'
import Banner from '../../components/Banner'
import '../../styles/globals.css'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Rasheed Blog',
  description: 'Generated by Rasheed Blog',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  )
}
